[package]
name = "try-rspc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.17"
rspc = { version = "0.1.2", features = ["axum"]}
tokio = { version = "1.21.2", features = ["full"] }
