[package]
name = "try-rspc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspc = "0.1.2"
tokio = { version = "1.21.2", features = ["full"] }
